// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7CvtBrqewl1XUbtNxiDlFj8V5JPBXu2s',
    appId: '1:744276050262:web:854ae6c208cee96f8656f7',
    messagingSenderId: '744276050262',
    projectId: 'ogoru-8e6e2',
    authDomain: 'ogoru-8e6e2.firebaseapp.com',
    storageBucket: 'ogoru-8e6e2.firebasestorage.app',
    measurementId: 'G-1B25S813EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz-viy0NzIxc8KU3MyrXPHg_e_LlRqEIc',
    appId: '1:744276050262:android:78e4269e8deca1d88656f7',
    messagingSenderId: '744276050262',
    projectId: 'ogoru-8e6e2',
    storageBucket: 'ogoru-8e6e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR4y_bTyUJafk7wb8rFAZmWSCji-RuRLY',
    appId: '1:744276050262:ios:a7f6c1b21bb4a9a88656f7',
    messagingSenderId: '744276050262',
    projectId: 'ogoru-8e6e2',
    storageBucket: 'ogoru-8e6e2.firebasestorage.app',
    iosBundleId: 'com.example.ogore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR4y_bTyUJafk7wb8rFAZmWSCji-RuRLY',
    appId: '1:744276050262:ios:a7f6c1b21bb4a9a88656f7',
    messagingSenderId: '744276050262',
    projectId: 'ogoru-8e6e2',
    storageBucket: 'ogoru-8e6e2.firebasestorage.app',
    iosBundleId: 'com.example.ogore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7CvtBrqewl1XUbtNxiDlFj8V5JPBXu2s',
    appId: '1:744276050262:web:744e1ec0d2af32cf8656f7',
    messagingSenderId: '744276050262',
    projectId: 'ogoru-8e6e2',
    authDomain: 'ogoru-8e6e2.firebaseapp.com',
    storageBucket: 'ogoru-8e6e2.firebasestorage.app',
    measurementId: 'G-VDJL98D6Y5',
  );
}
